### ISSUE TITLE
Update please?

### ISSUE THREAD

**Issue by WhoMI7** [mason-h/mpv-composition-guides#1]
Too outdated, can't get it to work

**Comment by Ares-0** [comment]
What version of mpv?

**Comment by Ares-0** [comment]
Hm works for me as of `mpv 0.35.0-317-g9880b06a`
Could you run it from cmd and paste any warnings / errors that show up?

**Comment by WhoMI7** [comment]
I update mpv every week, should be latest.
But the problem is I can't seem to get what should I add in `input.conf` for it to work. `w script-binding M.cycle_guide` didn't work.

Plus I have `input-default-bindings=no` in my `mpv.conf` so using `g` is a no go.
So what I am requesting is an update with which users can use any keybind and maybe a different.

Plus the `local directory = os.getenv("USERPROFILE") .. "/AppData/Roaming/mpv/scripts/composition_guides/guides/"` should be more flexible instead it should just use `~~/scripts/composition_guides/guides`

Also, from readme: `Scripts are usually placed in ~/.mpv/scripts/ (macOS/Linux) or %AppData%\mpv\scripts\ (Windows). Put the entire folder in this directory. Do not rearrange individual files or directories.
`
But there is not mentioned what the name of the folder should be. I had to manually change folder name from `mpv-composition-guides-master` to `composition_guides`.
Plus I've had a lot of trouble with older scripts breaking [uosc](https://github.com/tomasklaen/uosc)'s functionality. Maybe this will to even if it worked.

**Comment by Ares-0** [comment]
Those first two can be fixed in main.lua but yeah that shouldn't be a requirement. 

> So what I am requesting is an update with which users can use any keybind and maybe a different.

Ill look into getting that working for input.conf

> script directory reference

Yep I can make that more user friendly as well

> Folder name

Aaah I see, it downloads as `mpv-composition-guides-master`. Troublesome, Ill see what I can do

- [ ] Add keybind to input.conf
- [ ] Script directory more flexible
- [ ] Folder name documentation or standardization
- [ ] uosc compat?

Thanks for the feedback

**Comment by Ares-0** [comment]
@BhaturaGuy, Update for you

> Folder name / script directory fetching

Now uses `mp.get_script_directory()` so whatever the folder is called it will be able to load the main.lua.
As long as `scripts/folder_name/main.lua` and `scripts/folder_name/guides/...` is intact, `folder_name` can be whatever.

> Add keybind to input.conf

`g` will remain the default keybind, which will be added by default. 
Users who know what they're doing can easily change it in main.lua (e.g. `local key = 'q'`) or disable it by making it nil (`local key = nil`) or blank (`local key = ''`).

Users may now also use the built-in `script-binding` to bind scripts `comp_guide_cycle`, `comp_guide_clear`, and `comp_guide_43` in `input.conf` to set their keybinds just how they like it.
e.g. `h script-binding comp_guide_cycle` 

If users are using `--no-input-default-bindings` or the like, the onus is kind of on them to replace the binding setups. Between the key-bindings above and the commented out `mp.add_forced_key_binding(...)` in `main.lua:M.Main()`, there should be no problem setting up keybinds for each workflow. Out of the box though, it's `g`.

> uosc

Tested on `5fbfac3`, seems to work just fine. This script just uses the [OSD overlay-add](https://mpv.io/manual/stable/#command-interface-overlay-add) so I imagine any conflicts would be on the keybind side or mpv osd updates which Ill try and keep an eye on.

Cheers

**Comment by WhoMI7** [comment]
Worked but breaking uosc.

https://user-images.githubusercontent.com/93109835/213679825-f6261b12-6861-4cc8-8eb0-3608db2b0ef8.mp4

**Comment by Ares-0** [comment]
That's.. very odd behavior. If you want to post all of your exact uosc settings I dont mind debugging a bit.
